### ISSUE TITLE
visualizing affinity map between a seed token and other patch features

### ISSUE THREAD

**Issue by duan-song** [wysoczanska/clip_dinoiser#12]
Hi, I find a beautiful heatmap visualization in the fig. 4 of the paper, the affinity map between a selected seed token and other patch features. Could you please provide the code for visualizing affinity map？

**Comment by wysoczanska** [comment]
Hi, thanks for your interest! please take a look at: https://github.com/wysoczanska/clip_dinoiser/issues/9

**Comment by duan-song** [comment]
> Hi, thanks for your interest! please take a look at: #9

Thank you! I successfully generate the visualized affinity map.

**Comment by wysoczanska** [comment]
Closing the issue then :)
