### ISSUE TITLE
How do you calculate the patch affinity?

### ISSUE THREAD

**Issue by ascetic-monk** [wysoczanska/clip_dinoiser#2]
First, thanks for your exciting work. But I still feel a little confused about the construction of patch affinity for DINO. To my acknowledge, the value embeddings in the last attention layers are organized in form of multi-head structure, how do you deal with the multi-head value embeddings for calculating the similarity? Flattening the heads? Or calculating the similarities per head and averaging them? Hope for your answering.

**Comment by wysoczanska** [comment]
Hi, thank you for your interest in our work! That's a very good point. We indeed flatten the heads, therefore one per-patch DINO embedding is a concatenation of the per-patch values from all the heads. I hope it makes it clearer.

**Comment by ascetic-monk** [comment]
That is clear. Thanks for answering!
